sections/patients.md
=> Added patient invoice information to patients endpoint

readme.md
=> Sort (almost) all the things

readme.md, sections/practitioner_reference_numbers.md, sections/practitioners.md
=> Practitioner Reference Number and Practitioner description 

sections/invoice_items.md
Invoice items have a "loose" connection to a billable item or a product.
=> Add billable item or product relation

sections/products.md, sections/settings.md
This adds a few improvements to our API:
- You can now search products by name
- Products will now also have the **serial_number** attribute
- Settings will have the **subdomain** attribute
=> Search products by name. Add serial number and subdomain.

sections/patients.md
=> Add documentation for patient archival end point

sections/billable_items.md
The MD wasn't correct, and so the endpoint links to page anchors weren't working. Corrected.
=> Corrected End-point Anchor links

sections/billable_items.md
=> Missing underscore in GET billable_items endpoint

readme.md, sections/treatment_note_templates.md, sections/treatment_notes.md
=> Treatment notes

sections/practitioner_reference_numbers.md
Reference to Appointments in Filtering section changed to Practitioner References Numbers
=> Incorrect reference to Appointments corrected

sections/treatment_notes.md
We don't allow this to be set.
=> Remove practitioner_id from treatment note create params

sections/treatment_note_templates.md
=> Add filter fields

sections/contacts.md
=> Add filtering on contact type_code

sections/bookings.md
Just wanted to be clear about Array/list filtering. This isn't specifically listed in any other endpoint, so calling it out with extra detail as to how this is done.
=> Clarity with respect to filtering on lists (Array)

guides/uploading_patient_attachments.md, sections/patient_attachments.md
This is still WIP. Need to write the endpoint descriptions and finalize the API in Cliniko.
=> Patient attachments

guides/testing_api_client_tls.md, readme.md
For more information: https://community.cliniko.com/t/requiring-tls-1-2-on-the-cliniko-api-may-1-2018/461
=> Update TLS requirement

sections/appointment_types.md
Fix https://github.com/redguava/cliniko-api/issues/204
=> Add treatment note template to appointment type

sections/attendees.md
http://local.cliniko.dev:3000 -> https://api.cliniko.com
=> Update local.cliniko.dev references in response links

sections/treatment_notes.md
Because this is VERY important!
=> Include booking_id prop in POST/Create example

sections/unavailable_blocks.md
=> Remove misleading notes

sections/patients.md
=> Add `appointment_notes` prop

guides/uploading_patient_attachments.md
Added a full request to the patient attachments upload guide, demo'ing how to set description and filename props.
=> Added more props to patient_attachments guide request

sections/referral_sources.md
Wrote 'Response' in headers. Should have been 'Request'.
=> Typo: response -> request

sections/patients.md
=> Add information regarding merged patient

guides/uploading_patient_attachments.md
There's a PR at Cliniko that updates the version of the AWS we use to handle file uploads. This changes the fields on the presigned post form a bit. This PR contains the accompanying documentation changes.
=> Update presigned post fields

.gitignore, guides/sharding.md
Adding sharding announcement. This will change to _sharded_ once live.
=> Sharding doc

sections/contacts.md
=> Add new filters to contacts

sections/patients.md
This end point will be used for real deletion at some point.
=> Remove delete from patients

sections/patients.md
Support for this prop was added last year. Updating docs.
=> Add prop `accepted_email_marketing` to patient responses
